:set directory=$XDG_CACHE_HOME/vim,/tmp
:set backupdir=$XDG_CACHE_HOME/vim,/tmp
:set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
:set runtimepath=$XDG_TERM_CONFIG/nvim,$VIM,$VIMRUNTIME

:set number

:let $MYVIMRC="$XDG_TERM_CONFIG/nvim/vimrc"
