#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.var"
export XDG_DATA_HOME="$HOME/.local/share"

export XDG_SESSION_TYPE="x11"
export XDG_CONFIG_DIRS="/etc/xdg"

export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_VIDEOS_DIR="$HOME/Videos"

export XCURSOR_SIZE=32

if [ -d "$XDG_CONFIG_HOME"/xinitrc.d ]; then
  for file in "$XDG_CONFIG_HOME"/xinitrc.d/?*.sh ; do
    [ -x "$file" ] && source "$file"
  done
  unset file
fi

function init_session() {
  xset b off
  
  source "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"

    . "$XDG_CONFIG_HOME/_main/X11/xprofile"
    exec bspwm -c "$XDG_CONFIG_HOME/_main/bspwm/config.bash"
}

if [ ! "$PWD" = "$HOME" ]
then
  pushd "$HOME"
  init_session
  popd
else
  init_session
fi
