#!/usr/bin/env bash

function init_session() {
  xset b off
  
  source "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"

  systemctl --user import-environment DISPLAY XAUTHORITY
   if which dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
   fi

    . "$XDG_CONFIG_HOME/_main/X11/.xprofile"
    
    exec bspwm -c "$XDG_CONFIG_HOME/_main/bspwm/config.bash"
}

if [ ! "$PWD" = "$HOME" ]
then
  pushd "$HOME"
  init_session
  popd
else
  init_session
fi

