#!/usr/bin/env bash

export XDG_MAIN_CONFIG="$HOME/.config/_main"
export XDG_SHELL_CONFIG="$HOME/.config/_shell"
export XDG_TERM_CONFIG="$HOME/.config/_term"
export XDG_UI_CONFIG="$HOME/.config/_ui"
export XDG_MISC_CONFIG="$HOME/.config/_misc"
export XDG_ETC_CONFIG="$HOME/.config/_etc"

export XDG_CONFIG_HOME="$XDG_ETC_CONFIG"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.var"
export XDG_DATA_HOME="$HOME/.local/share"

export XDG_CONFIG_DIRS="/etc/xdg"

export XDG_DESKTOP_DIR="$HOME/desktop"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_PICTURES_DIR="$HOME/pictures"
export XDG_VIDEOS_DIR="$HOME/videos"

export QT_QPA_PLATFORMTHEME="gtk2" # Make QT use gtk2 theme

export XCURSOR_SIZE=24

userresources=$XDG_MAIN_CONFIG/X11/Xresources/config.x
usermodmap=$XDG_MAIN_CONFIG/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -I "$XDG_MAIN_CONFIG/X11/Xresources" -merge "$userresources"
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi


if [ -d "$XDG_MAIN_CONFIG"/X11/xinitrc.d ]; then
  for file in "$XDG_MAIN_CONFIG"/X11/xinitrc.d/?*.sh ; do
    [ -x "$file" ] && source "$file"
  done
  unset file
fi

function init_session() {
    . "$XDG_MAIN_CONFIG/X11/Xprofile"
    
    case $(tty | cut -b9-) in
    (1) exec bspwm -c "$XDG_MAIN_CONFIG/bspwm/config.bash" ;;
    esac
}

if [ ! "$PWD" = "$HOME" ]
then
  pushd "$HOME"
  init_session
  popd
else
  init_session
fi
