#!/usr/bin/env bash

xset b off
xsetroot -cursor_name left_ptr
xset mouse 0 0

fcitx5 -d
setxkbmap -layout us
unclutter --timeout 10 &

# Resolution
# Make sure to give the script executable permission
# $HOME/.local/bin/setres <output> <x> <y> <rate>
# wal -a 95 -i $XDG_UI_CONFIG/wallpapers/
