#!/usr/bin/env bash

setxkbmap -layout us
hsetroot -solid "#050505"

setxkbmap -layout us &
fcitx -d &

# Resolution
# Make sure to give the script executable permission
# $HOME/.local/bin/setres <output> <x> <y> <rate>
