#!/usr/bin/env bash

hsetroot -solid "#050505"

xset b off
xsetroot -cursor_name left_ptr
xset mouse 0 0

setxkbmap -layout us &
fcitx -d &

# Resolution
# Make sure to give the script executable permission
# $HOME/.local/bin/setres <output> <x> <y> <rate>
